import { Header } from '@/components'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={inter.className}
        style={{
          backgroundColor: '#033649'
        }}
      >
        <div
          style={{
            borderRadius: 10,
            backgroundColor: 'white',
            marginTop: 100,
            padding: 25,
            boxShadow: '2px 2px 10px black',
            width: '75vw',
            marginLeft: 'auto',
            marginRight: 'auto'
          }}
        >
          <Header />
          {children}
        </div>
      </body>
    </html>
  )
}
